name: flutter_template
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # flutter国际化
    sdk: flutter
  cupertino_icons: ^1.0.3 # cupertinoIcons
  webview_flutter: ^2.0.8 # webView
  calculate: ^0.0.9 # double类计算支持
  cached_network_image: ^2.2.0+1 #图片缓存
  path_provider: ^2.0.2 # 获取应用程序目录
  dio: ^4.0.0 # http支持
  shared_preferences: ^2.0.6 # 数据持久化存储
  package_info: '>=0.4.0+18 <2.0.0' # 应用程序包的信息
  yaml: ^3.1.0 # yml文件内容解析器
  file: ^6.1.2 # 内存文件系统
  # cipher2: ^0.3.5 # aes-128-cbc加密[由于版本关系在Android X设备无法使用]
  # pointycastle: ^1.0.2 # 加密基础库
  encrypt: ^4.0.1 # aes-128-cbc加密
  archive: ^2.0.13 # 解压缩
  permission_handler: ^8.1.1 # 动态权限申请[android]
  shelf: ^1.1.4 # Web服务器
  shelf_static: ^0.2.8 # shelf静态资源中间件
  # bot_toast: ^3.0.0 # 全局的弹框
  # fluro: ^1.6.3 # 路由管理工具[替代官方路由]
  provider: ^5.0.0 # 状态管理[实现基类: InheritedWidget]
  # rxdart: ^0.27.1 # 状态管理[实现基类: Stream]
  mqtt_client: ^8.2.0 # mqtt推送
  device_info: ^2.0.2 # 设备信息
  # url_launcher: ^6.0.7 # 吊起外部资源[支持电话、短信等]
  # qr_flutter: ^4.0.0 # 生成二维码
  # scan: ^1.4.3 # 扫描二维码
  # image_gallery_saver: 1.5.0 # 保存图片到相册
  jpush_flutter: ^2.1.5 # 激光推送
  # image_picker: 0.8.0+4 # 图库

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  # 仅在这里输出的路径才会被打包到最终的application中
    # 文件[json]
    - assets/json/ # 可单独跟country_code.json以便仅打包该文件
    # 图片
    - assets/images/
    # 国际化文件
    - assets/locale/
    # 字体文件
  fonts:
    - family: iconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
          weight: 800

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
