name: flutter_template
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.16.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # flutter国际化
    sdk: flutter
  cupertino_icons: ^1.0.6 # cupertinoIcons
  webview_flutter: ^4.4.1 # webView
  # decimal: ^2.3.3 # double类计算支持
  cached_network_image: ^3.3.0 #图片缓存
  path_provider: ^2.1.1 # 获取应用程序目录
  dio: ^5.3.3 # http支持
  shared_preferences: ^2.2.2 # 数据持久化存储
  package_info_plus: ^3.1.2 # 应用程序包描述信息
  yaml: ^3.1.2 # yml文件内容解析器
  file: ^7.0.0 # 内存文件系统
  # cipher2: ^0.3.5 # aes-128-cbc加密[由于版本关系在Android X设备无法使用]
  # pointycastle: ^3.7.3 # 加密基础库
  encrypt: ^5.0.3 # aes-128-cbc加密
  archive: ^3.4.6 # 解压缩
  permission_handler: ^11.0.1 # 动态权限申请[android]
  shelf: ^1.4.1 # Web服务器
  shelf_static: ^1.1.2 # shelf静态资源中间件
  # overlay_support: ^2.1.0 # 顶部通知
  provider: ^6.0.5 # 状态管理[实现基类: InheritedWidget]
  # rxdart: ^0.27.7 # 状态管理[实现基类: Stream]
  # pinput: ^3.0.1 # 自动填充短信验证码（自带输入框）
  # mqtt_client: ^10.0.0 # mqtt推送
  device_info_plus: ^9.1.0 # 设备信息
  url_launcher: ^6.2.1 # 吊起外部资源[支持电话、短信等]
  qr_flutter: ^4.1.0 # 生成二维码
  scan: ^1.6.0 # 扫描二维码
  image_gallery_saver: ^2.0.3 # 保存图片到相册
  # jpush_flutter: ^2.5.0 # 激光推送
  connectivity_plus: ^5.0.2 # 网络链接状态
  # wakelock: ^0.6.2 # App常亮显示
  # image_cropper: ^5.0.0 # 图片裁剪
  image_picker: ^1.0.4 # 图库
  flutter_xupdate: ^3.0.0 # Android应用内升级
  flutter_html: 3.0.0-beta.2 # html渲染成widget
  # local_auth: ^2.1.7 #指紋/面部
  pub_semver: ^2.1.4 # 版本约束检查
  google_fonts: ^4.0.4
  image: ^4.1.3
  lottie: ^3.0.0 # 解析并渲染 Adob​​e After Effects 动画
  safe_device: ^1.1.4 # 检测设备安全
  share_plus: ^7.2.1 # 分享应用
  shelf_proxy: ^1.0.4
  shelf_router: ^1.1.4
  belatuk_range_header: ^6.1.0
  stomp_dart_client: ^1.0.2
  go_router: ^13.1.0 # 路由管理: https://pub.dev/documentation/go_router/latest/topics/Get%20started-topic.html
  # uni_links: ^0.5.1 # schema 协议

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  # 仅在这里输出的路径才会被打包到最终的application中
    # 文件[json]
    - assets/json/ # 可单独跟country_code.json以便仅打包该文件
    # 图片
    - assets/images/
    # 国际化文件
    - assets/locale/
    # 字体文件
  fonts:
    - family: iconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
          weight: 800

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
